### ISSUE TITLE
License clarification for older versions

### ISSUE THREAD

**Issue by pinty** [stevemao/left-pad#51]
Hello @stevemao 

Currently I'm using the version 0.0.3 of this module and there is no clearly specified the license and I cannot find this version on your repository either. The only information available is the one from package.json which seems to be "license: BSD". What license does apply for this version? Is it BSD? What version of BSD would apply?

Thank you!

**Comment by stevemao** [comment]
I don't know... Don't really care either. Do whatever you want.

**Comment by spectejb** [comment]
@stevemao - I hear you on not caring!  

Would love to use left pad - any chance you would consider [MIT](https://opensource.org/licenses/MIT) or [BSD](https://opensource.org/licenses/BSD-3-Clause)?  The WTFPL has good intentions but one of those two would really expand the potential audience since they are recognized by the Open Source Initiative (and therefore make my life easier with our legal department! haha).   

Thanks, in advance, for your help making that easier on me and I am sure a lot of others! :)

btw, fwiw, GitHub makes it easy to create the license file with the text!

**Comment by stevemao** [comment]
@spectejb mate, PR for whatever you want it to be :)

**Comment by spectejb** [comment]
Just submitted a PR to add MIT license file + remove WTFPL references.  Thanks again for being open to this!  You rock.

**Comment by szdc** [comment]
@stevemao could you publish a new version to reflect the license change in npm please?
